services:
  # Serviço PostgreSQL para desenvolvimento
  db:
    image: postgres:15-alpine
    container_name: loja_sapatos_db
    environment:
      POSTGRES_DB: loja_sapatos
      POSTGRES_USER: loja_sapatos_user
      POSTGRES_PASSWORD: senha123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Serviço Spring Boot para desenvolvimento
  app:
    build: .
    container_name: loja_sapatos_app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: loja_sapatos
      DATABASE_USERNAME: loja_sapatos_user
      DATABASE_PASSWORD: senha123
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
