services:
  # Serviço PostgreSQL para desenvolvimento
  db:
    image: postgres:15-alpine
    container_name: loja_sapatos_db
    environment:
      POSTGRES_DB: loja_sapatos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Serviço Spring Boot para desenvolvimento
  app:
    build: .
    container_name: loja_sapatos_app
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/loja_sapatos
      DB_USERNAME: postgres
      DB_PASSWORD: senha123
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
