

services:
  # Serviço PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: loja_sapatos_db
    environment:
      POSTGRES_DB: loja_sapatos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Serviço Spring Boot
  app:
    build: .
    container_name: loja_sapatos_app
    environment:
      # Sobrescrever configurações para Docker conforme resultados da busca
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/loja_sapatos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
